#! /bin/sh

### BEGIN INIT INFO
# Provides:          shairport
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: AirTunes daemon
# Description: AirTunes daemon
### END INIT INFO

N=/etc/init.d/shairport

DAEMON=/usr/local/bin/shairport.pl
DESC="AirTunes daemon"
NAME=shairport
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
RUNAS=pi
DAEMON_ARGS=""

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


set -e

case "$1" in
  start)
	if [ ! -n "$SHAIRPORT_NAME" ]; then 
		SHAIRPORT_NAME=$( echo "ShairPort $$ on" `hostname`);
	fi

	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --pidfile $PIDFILE --start --name $NAME --exec $DAEMON --background  --make-pidfile --chuid $RUNAS -- $DAEMON_ARGS -a "'$SHAIRPORT_NAME'"
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 5
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  reload|restart|force-reload)
	$0 stop 
	$0 start
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0
