#!/bin/sh

user=pablo

useradd -m $user
usermod -G audio $user
usermod -G video $user

# Gives the user full sudo rights
echo "$user  ALL=(ALL) ALL" >> /etc/sudoers

# This disables the default "pi" account, so be cautious
usermod --expiredate 1 pi

mkdir ~$user/.ssh
wget -O ~$user/.ssh/authorized_keys https://dl.dropbox.com/u/5290/ssh/authorized_keys
chown -R $user.$user ~$user/.ssh
