#!/bin/sh

user=pablo

useradd -s /bin/bash -m $user
usermod -G audio,video $user

# Gives the user full sudo rights
echo "$user  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# This disables the default "pi" account, so be cautious
usermod --expiredate 1 pi

mkdir /home/$user/.ssh
wget -O /home/$user/.ssh/authorized_keys https://dl.dropbox.com/u/5290/ssh/authorized_keys
chown -R $user.$user /home/$user/.ssh
